[toolchain]
anchor_version = "0.32.1"

[features]
seeds = false
skip-lint = false

[programs.devnet]
repo_registry = "8d7FrUUG4sKQRsKpUDTimKb4c2MQqWVfkPFhM79CY6Ge"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "anchor test"
